// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd) {
    return dd.drive({
      it: "formats resolved filename",
      i: ['wherever/it/can/be/in/whatever/environment/node_modules/ddry/index.js'],
      e: 'node_modules/ddry/index.js'
    });
  };

}).call(this);
