// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  module.exports = function(dd, that) {
    return dd.drive({
      it: "includes 'tape'",
      i: [],
      e: 'node_modules/tape/index.js'
    });
  };

}).call(this);
