// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var spec;

  spec = require('ddry/modular')();

  spec.apply({
    title: 'ddry and Tape dependencies presence',
    spec: 'spec/usecase',
    moduleTitles: {
      dependencies: 'ddry-tape dependencies'
    },
    outside: {
      dependencies: 'usecase/dependencies'
    }
  });

}).call(this);
